# fly.toml app configuration file generated for rusve-client on 2023-04-23T21:15:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rusve-client"
primary_region = "arn"

[mounts]
  destination = "/app/files"
  source = "files"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
