[package]
name = "rusve-notes"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
prost = "0.11.9"
tonic = "0.9.2"
tonic-build = "0.9.2"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1.12"
futures-core = "0.3.28"
futures-util = "0.3.28"
anyhow = "1.0.69"
serde = "1.0.154"

# Database
time = "0.3.20"
uuid = "1.3.2"
deadpool-postgres = "0.10.5"
diesel = { version = "2.0.4", features = ["postgres", "time", "uuid", "numeric"] }
dotenvy = "0.15.7"
