# fly.toml app configuration file generated for rust-users on 2023-04-20T09:23:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-users"
primary_region = "arn"

[env]
  PORT = 443
  ENV = "production"
  SECRET = "my-rust-secret"

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[services]
  http_checks = []
  script_checks = []
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"
    tls_options = { "alpn" = ["h2"] }

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
