version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /client
    build:
      context: ./client
      target: dev
      args:
        ENV: development
        COOKIE_DOMAIN: .127.0.0.1
        PUBLIC_OAUTH_URL: http://127.0.0.1:8090
        USERS_URI: service-users
        UTILS_URI: service-utils
        NOTES_URI: service-notes
        UPSEND_KEY: ${UPSEND_KEY}
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000

  service-oauth:
    container_name: rusve-service-oauth
    working_dir: /app
    build:
      context: ./service-oauth
      target: dev
    volumes:
      - ./service-oauth/src:/app/src
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
      SERVER_URL: http://127.0.0.1:8090
      CLIENT_URL: http://127.0.0.1:3000
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - 8090:443

  service-users:
    container_name: rusve-service-users
    working_dir: /app
    build:
      context: ./service-users
      target: dev
    volumes:
      - ./service-users/src:/app/src
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
      CLIENT_URL: http://127.0.0.1:3000/subscription
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}

  service-notes:
    container_name: rusve-service-notes
    working_dir: /app
    build:
      context: ./service-notes
      target: dev
    volumes:
      - ./service-notes/src:/app/src
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-notes&user=postgres&password=12345&dbname=notes

  service-utils:
    container_name: rusve-service-utils
    working_dir: /app
    build:
      context: ./service-utils
      target: dev
    volumes:
      - ./service-utils/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key

  db-users:
    container_name: rusve-db-users
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users

  db-notes:
    container_name: rusve-db-notes
    image: postgres:15.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: notes

  db-utils:
    container_name: rusve-db-utils
    image: postgres:15.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users

