version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /client
    build:
      context: ./client
      target: dev
      args:
        ENV: development
        COOKIE_DOMAIN: .127.0.0.1
        PUBLIC_AUTH_URL: http://127.0.0.1:8090
        USERS_URI: service-users
        UTILS_URI: service-utils
        NOTES_URI: service-notes
        UPSEND_KEY: ${UPSEND_KEY}
        JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000

  service-auth:
    container_name: rusve-service-auth
    working_dir: /app
    build:
      context: ./service-auth
      target: dev
    volumes:
      - ./service-auth/src:/app/src
    environment:
      PORT: 443
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
      AUTH_URL: http://127.0.0.1:8090
      CLIENT_URL: http://127.0.0.1:3000
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8090:443

  service-users:
    container_name: rusve-service-users
    working_dir: /app
    build:
      context: ./service-users
      target: dev
    volumes:
      - ./service-users/src:/app/src
    environment:
      PORT: 443
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
      CLIENT_URL: http://127.0.0.1:3000
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
      JWT_SECRET: ${JWT_SECRET}

  service-notes:
    container_name: rusve-service-notes
    working_dir: /app
    build:
      context: ./service-notes
      target: dev
    volumes:
      - ./service-notes/src:/app/src
    environment:
      PORT: 443
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-notes&user=postgres&password=12345&dbname=notes
      USERS_URL: http://service-users:443
      JWT_SECRET: ${JWT_SECRET}

  service-utils:
    container_name: rusve-service-utils
    working_dir: /app
    build:
      context: ./service-utils
      target: dev
    volumes:
      - ./service-utils/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET_NAME: rusve
      JWT_SECRET: ${JWT_SECRET}
