version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /client
    build:
      context: ./client
      target: dev
      args:
        ENV: development
        PUBLIC_DOMAIN: http://127.0.0.1:3000
        PUBLIC_API_KEY: PUBLIC_API_KEY
        PUBLIC_AUTH_DOMAIN: PUBLIC_AUTH_DOMAIN
        USERS_URI: service-users
        UTILS_URI: service-utils
        NOTES_URI: service-notes
        STRIPE_API_KEY: STRIPE_KEY
        SERVICE_ACCOUNT: SERVICE_ACCOUNT
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000

  service-user:
    container_name: rusve-service-users
    working_dir: /app
    build:
      context: ./service-users
      target: dev
    volumes:
      - ./service-users/src:/app/src
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users

  service-notes:
    container_name: rusve-service-notes
    working_dir: /app
    build:
      context: ./service-notes
      target: dev
    volumes:
      - ./service-notes/src:/app/src
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=db-notes&user=postgres&password=12345&dbname=notes

  service-utils:
    container_name: rusve-service-utils
    working_dir: /app
    build:
      context: ./service-utils
      target: dev
    volumes:
      - ./service-utils/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key
