version: "3"
services:
    db-users:
        container_name: rusve-db-users
        image: postgres:15.1
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: users

    db-utils:
        container_name: rusve-db-utils
        image: postgres:15.1
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: users

    db-notes:
        container_name: rusve-db-notes
        image: postgres:15.1
        ports:
            - 3306:3306
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: notes
