version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /app
    build:
      context: ./client
      target: dev
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  service-users-rust:
    container_name: rusve-service-users-rust
    working_dir: /app
    build:
      context: ./service-users
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-users/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://?host=service-users-db&user=postgres&password=12345&dbname=users
        # DATABASE_URL: postgres://mpiorowski:mrCiUac1dHS3@ep-green-leaf-150124.eu-central-1.aws.neon.tech/users?sslmode=require&options=endpoint%3Dep-green-leaf-150124
        # DATABASE_URL_POOL: postgres://mpiorowski:mrCiUac1dHS3@ep-green-leaf-150124-pooler.eu-central-1.aws.neon.tech/users?sslmode=require&options=endpoint%3Dep-green-leaf-150124-pooler
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key

  service-users-go:
    container_name: rusve-service-users-go
    working_dir: /app
    build:
      context: ./service-users-go
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-users-go/src:/app/src
      - ./files:/app/files
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=service-users-db&user=postgres&password=12345&dbname=users
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key

  service-notes-rust:
    container_name: rusve-service-notes-rust
    working_dir: /app
    build:
      context: ./service-notes
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-notes/src:/app/src
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: mysql://vym9rxqqpib4fkcszhu9:pscale_pw_fHWrmvgEFp2NzVXy5GmUDi7LxUrBhMzr6UetBLxP1j8@aws.connect.psdb.cloud/notes
        # DATABASE_URL: postgresql://?host=service-notes-db&user=postgres&password=12345&dbname=notes
        # DATABASE_URL: postgres://mpiorowski:mrCiUac1dHS3@ep-green-leaf-150124.eu-central-1.aws.neon.tech/notes?sslmode=require&options=endpoint%3Dep-green-leaf-150124
        # DATABASE_URL_POOL: postgres://mpiorowski:mrCiUac1dHS3@ep-green-leaf-150124-pooler.eu-central-1.aws.neon.tech/notes?sslmode=require&options=endpoint%3Dep-green-leaf-150124-pooler

  service-notes-go:
    container_name: rusve-service-notes-go
    working_dir: /app
    build:
      context: ./service-notes-go
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-notes-go:/app
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=service-notes-db&user=postgres&password=12345&dbname=notes

  directus:
    container_name: rusve-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
      DB_CLIENT: sqlite3
      DB_FILENAME: ./database/data.db
      CACHE_ENABLED: false
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: d1r3ctu5
