version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /app
    build:
      context: ./client/
      target: dev
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  service-users-rust:
    container_name: rusve-service-users-rust
    working_dir: /app
    build:
      context: ./service-users-rust
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-users-rust/src:/app/src
    depends_on:
      - service-users-db
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://postgres:12345@service-users-db/users

  service-users-go:
    container_name: rusve-service-users-go
    working_dir: /app
    build:
      context: ./service-users-go
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-users-go:/app
    depends_on:
      - service-users-db
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://postgres:12345@service-users-db/users

  service-users-db:
    container_name: rusve-service-users-db
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users

  service-utils:
    container_name: rusve-service-utils
    working_dir: /app
    build:
      context: ./service-utils
      dockerfile: Dockerfile.dev
    volumes:
      - ./files:/app/files
      - ./service-utils/src:/app/src
    depends_on:
      - service-utils-db
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://?host=service-utils-db&user=postgres&password=12345&dbname=utils
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key

  service-utils-db:
    container_name: rusve-service-utils-db
    image: postgres:15.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: utils

  service-notes-rust:
    container_name: rusve-service-notes-rust
    working_dir: /app
    build:
      context: ./service-notes-rust
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-notes-rust/src:/app/src
    depends_on:
      - service-notes-db
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://postgres:12345@service-notes-db/notes

  service-notes-go:
    container_name: rusve-service-notes-go
    working_dir: /app
    build:
      context: ./service-notes-go
      dockerfile: Dockerfile.dev
    volumes:
      - ./service-notes-go:/app
    depends_on:
      - service-notes-db
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://postgres:12345@service-notes-db/notes

  service-notes-db:
    container_name: rusve-service-notes-db
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: notes

  directus:
    container_name: rusve-directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
      DB_CLIENT: sqlite3
      DB_FILENAME: ./database/data.db
      CACHE_ENABLED: false
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: d1r3ctu5
