version: "3"
services:
    client:
        container_name: rusve-client
        working_dir: /app
        build:
            context: ./client
            target: dev
        volumes:
            - ./client:/app
        ports:
            - 3000:3000

    service-users-rust:
        container_name: rusve-service-users-rust
        working_dir: /app
        build:
            context: ./service-users-rust
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-users-rust/src:/app/src
            - ./files:/app/files
        environment:
            PORT: 443
            ENV: development
            DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users

    service-users-go:
        container_name: rusve-service-users-go
        working_dir: /app
        build:
            context: ./service-users-go
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-users-go/src:/app/src
            - ./files:/app/files
        environment:
            ENV: development
            PORT: 443
            DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users

    service-utils-rust:
        container_name: rusve-service-utils-rust
        working_dir: /app
        build:
            context: ./service-utils-rust
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-utils-rust/src:/app/src
            - ./files:/app/files
        environment:
            PORT: 443
            ENV: development
            DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
            BUCKET: bucket
            SENDGRID_API_KEY: sendgid-api-key

    service-utils-go:
        container_name: rusve-service-utils-go
        working_dir: /app
        build:
            context: ./service-utils-go
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-utils-go/src:/app/src
            - ./files:/app/files
        environment:
            PORT: 443
            ENV: development
            DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
            BUCKET: bucket
            SENDGRID_API_KEY: sendgid-api-key

    service-notes-rust:
        container_name: rusve-service-notes-rust
        working_dir: /app
        build:
            context: ./service-notes-rust
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-notes-rust/src:/app/src
        environment:
            ENV: development
            PORT: 443
            DATABASE_URL:
                mysql://admin:12345@db-notes:3306/notes

    service-notes-go:
        container_name: rusve-service-notes-go
        working_dir: /app
        build:
            context: ./service-notes-go
            dockerfile: Dockerfile.dev
        volumes:
            - ./service-notes-go:/app
        environment:
            ENV: development
            PORT: 443
            DATABASE_URL:
                admin:12345@tcp(db-notes:3306)/notes

    directus:
        container_name: rusve-directus
        image: directus/directus:latest
        ports:
            - 8055:8055
        environment:
            KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
            SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
            DB_CLIENT: sqlite3
            DB_FILENAME: ./database/data.db
            CACHE_ENABLED: false
            ADMIN_EMAIL: admin@example.com
            ADMIN_PASSWORD: d1r3ctu5
