version: "3"
services:
  client:
    container_name: rusve-client
    working_dir: /app
    build:
      context: ./client
      target: dev
      args:
        ENV: development
        PUBLIC_DOMAIN: http://localhost:3000
        PUBLIC_API_KEY: PUBLIC_API_KEY
        PUBLIC_AUTH_DOMAIN: PUBLIC_AUTH_DOMAIN
        URI_USERS_RUST: service-users-rust
        URI_USERS_GO: service-users-go
        URI_UTILS_RUST: service-utils-rust
        URI_UTILS_GO: service-utils-go
        URI_NOTES_RUST: service-notes-rust
        URI_NOTES_GO: service-notes-go
        URI_DIRECTUS: http://directus:8055
        STRIPE_API_KEY: STRIPE_KEY
        SERVICE_ACCOUNT: SERVICE_ACCOUNT
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  service-users-rust:
    container_name: rusve-service-users-rust
    working_dir: /app
    build:
      context: ./service-users-rust
      target: dev
    volumes:
      - ./service-users-rust/src:/app/src
    environment:
      PORT: 443
      ENV: development
      RUST_LOG: info
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
    command: sh -c "cargo run --bin main"

  service-users-go:
    container_name: rusve-service-users-go
    working_dir: /app
    build:
      context: ./service-users-go
      target: dev
    volumes:
      - ./service-users-go/src:/app/src
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=db-users&user=postgres&password=12345&dbname=users
    command: sh -c "go run /app/src/."

  service-notes-rust:
    container_name: rusve-service-notes-rust
    working_dir: /app
    build:
      context: ./service-notes-rust
      target: dev
    volumes:
      - ./service-notes-rust/src:/app/src
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=db-notes&user=postgres&password=12345&dbname=notes
    command: sh -c "cargo run --bin main"

  service-notes-go:
    container_name: rusve-service-notes-go
    working_dir: /app
    build:
      context: ./service-notes-go
      target: dev
    volumes:
      - ./service-notes-go:/app
    environment:
      ENV: development
      PORT: 443
      DATABASE_URL: postgresql://?host=db-notes&user=postgres&password=12345&dbname=notes
    command: sh -c "go run /app/src/."

  service-utils-rust:
    container_name: rusve-service-utils-rust
    working_dir: /app
    build:
      context: ./service-utils-rust
      target: dev
    volumes:
      - ./service-utils-rust/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key
    command: sh -c "cargo run --bin main"

  service-utils-go:
    container_name: rusve-service-utils-go
    working_dir: /app
    build:
      context: ./service-utils-go
      target: dev
    volumes:
      - ./service-utils-go/src:/app/src
      - ./files:/app/files
    environment:
      PORT: 443
      ENV: development
      DATABASE_URL: postgresql://?host=db-utils&user=postgres&password=12345&dbname=users
      BUCKET: bucket
      SENDGRID_API_KEY: sendgid-api-key
    command: sh -c "go run /app/src/."
