# fly.toml app configuration file generated for rusve-notes on 2023-04-23T20:56:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rusve-notes"
primary_region = "arn"

[env]
  ENV = "production"
  PORT = "443"
  SECRET = "my-rust-secret"
  URI_USERS = "https://rusve-users.fly.dev"

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  protocol = "tcp"
  internal_port = 443

  [[services.ports]]
    port = 443
    handlers = ["tls"]
    [services.ports.tls_options]
      alpn = ["h2"]

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
