# fly.toml file generated for rust-grpc-utils on 2023-03-13T00:35:05+01:00

app = "rust-grpc-utils"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]
  PORT = 443
  ENV = "production"
  SECRET = "my-jwt-secret"

[mounts]
  destination = "/app/files"
  source = "files"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 443
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443
    tls_options = { "alpn" = ["h2"] }

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
