# fly.toml app configuration file generated for directus-cms on 2023-05-09T09:39:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "directus-cms"
primary_region = "arn"

[env]
    ADMIN_EMAIL = "admin@example.com"
    ADMIN_PASSWORD = "d1r3ctu5"
    DB_CLIENT = "sqlite3"
    DB_FILENAME = "/data/data.db"
    KEY = "ed09b8277bac5ce36c2bcb387f187378"
    PUBLIC_URL = "https://directus-cms.fly.dev"
    SECRET = "b6fa56da9696a31af7296c26fbb39cd4"
    STORAGE_LOCAL_DRIVER = "local"
    STORAGE_LOCAL_ROOT = "/data/uploads"
    STORAGE_LOCATIONS = "local"
    CACHE_ENABLED = true

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
