name: Deploy
on:
  push:
    branches:
      - release-client/**
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  deploy-client:
    needs:
      - lint-client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create .env.prod file
        env: 
          ENV: production
          URI_USERS: ${{ secrets.URI_USERS }}
          URI_NOTES: ${{ secrets.URI_NOTES }}
          URI_UTILS: ${{ secrets.URI_UTILS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
          PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          touch .env.prod
          echo ENV="$ENV" >> .env.prod
          echo URI_USERS="$URI_USERS" >> .env.prod
          echo URI_UTILS="$URI_UTILS" >> .env.prod
          echo URI_NOTES="$URI_NOTES" >> .env.prod
          echo JWT_SECRET="$JWT_SECRET" >> .env.prod
          echo PUBLIC_API_KEY="$PUBLIC_API_KEY" >> .env.prod
          echo PUBLIC_AUTH_DOMAIN="$PUBLIC_AUTH_DOMAIN" >> .env.prod
          echo SERVICE_ACCOUNT='$SERVICE_ACCOUNT' >> .env.prod
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
