name: Deploy
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  deploy-users-rust:
    uses: ./.github/workflows/deploy-users-rust.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
  deploy-users-go:
    uses: ./.github/workflows/deploy-users-go.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
  deploy-utils-rust:
    uses: ./.github/workflows/deploy-utils-rust.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  deploy-utils-go:
    uses: ./.github/workflows/deploy-utils-go.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  deploy-notes-rust:
    uses: ./.github/workflows/deploy-notes-rust.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
  deploy-notes-go:
    uses: ./.github/workflows/deploy-notes-go.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
