name: Deploy
on:
  push:
    branches:
      - release/**
permissions:
  contents: read
  pull-requests: read
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-utils:
    uses: ./.github/workflows/lint-utils.yml
  lint-users:
    uses: ./.github/workflows/lint-users.yml
  lint-notes:
    uses: ./.github/workflows/lint-notes.yml
  lint-posts:
    uses: ./.github/workflows/lint-posts.yml
  deploy-client:
    needs:
      - lint-client
      - lint-utils
      - lint-users
      - lint-notes
      - lint-posts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create .env.prod file
        env: 
          ENV: production
          URI_UTILS: ${{ secrets.URI_UTILS }}
          URI_USERS: ${{ secrets.URI_USERS }}
          URI_NOTES: ${{ secrets.URI_NOTES }}
          URI_POSTS: ${{ secrets.URI_POSTS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
          PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          touch .env.prod
          echo ENV="$ENV" >> .env.prod
          echo URI_UTILS="$URI_UTILS" >> .env.prod
          echo URI_USERS="$URI_USERS" >> .env.prod
          echo URI_NOTES="$URI_NOTES" >> .env.prod
          echo URI_POSTS="$URI_POSTS" >> .env.prod
          echo JWT_SECRET="$JWT_SECRET" >> .env.prod
          echo PUBLIC_API_KEY="$PUBLIC_API_KEY" >> .env.prod
          echo PUBLIC_AUTH_DOMAIN="$PUBLIC_AUTH_DOMAIN" >> .env.prod
          echo SERVICE_ACCOUNT=\'$SERVICE_ACCOUNT\' >> .env.prod
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-utils:
    needs:
      - deploy-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: service-utils
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-users:
    needs:
      - deploy-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: service-users
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-notes:
    needs:
      - deploy-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: service-notes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-posts:
    needs:
      - deploy-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: service-posts
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
