name: Deploy
on:
  push:
    branches:
      - release/**
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-server:
    needs:
      - lint-client
    uses: ./.github/workflows/lint-server.yml
  deploy-users:
    needs:
      - lint-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: service-users
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
