name: Deploy
on:
  push:
    branches:
      - releasee/**
jobs:
  lint-client:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-client.yml
      #lint-utils:
      #  permissions:
      #    contents: write
      #    checks: write
      #  uses: ./.github/workflows/lint-utils.yml
  lint-users:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-users.yml
      #lint-notes:
      #  permissions:
      #    contents: write
      #    checks: write
      #  uses: ./.github/workflows/lint-notes.yml
      #lint-posts:
      #  permissions:
      #    contents: write
      #    checks: write
      #  uses: ./.github/workflows/lint-posts.yml
  deploy-client:
    permissions:
      contents: write
      id-token: write
    needs:
      - lint-client
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      URI_UTILS: ${{ secrets.URI_UTILS }}
      URI_USERS: ${{ secrets.URI_USERS }}
      URI_NOTES: ${{ secrets.URI_NOTES }}
      URI_POSTS: ${{ secrets.URI_POSTS }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  deploy-users:
    permissions:
      contents: write
      id-token: write
    needs:
      - lint-users
    uses: ./.github/workflows/deploy-users.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}


