name: Deploy
on:
  push:
    branches:
      - release/**
jobs:
  lint-client:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-client.yml
  lint-users:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-users.yml
  lint-utils:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-utils.yml
  lint-notes:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-notes.yml
  lint-posts:
    permissions:
      contents: write
      checks: write
    uses: ./.github/workflows/lint-posts.yml
  deploy-client:
    permissions:
      contents: write
      id-token: write
    needs:
      - lint-client
      - lint-users
      - lint-utils
      - lint-notes
      - lint-posts
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  deploy-users:
    permissions:
      contents: write
      id-token: write
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-users.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-utils:
    permissions:
      contents: write
      id-token: write
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-utils.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-notes:
    permissions:
      contents: write
      id-token: write
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-notes.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-posts:
    permissions:
      contents: write
      id-token: write
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-posts.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
