name: Deploy
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
      PUBLIC_AUTH_DOMAIN: ${{ secrets.PUBLIC_AUTH_DOMAIN }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  deploy-users:
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-users.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-users-go:
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-users-go.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-utils:
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-utils.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  deploy-notes:
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-notes.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
  deploy-notes-go:
    needs:
      - deploy-client
    uses: ./.github/workflows/deploy-notes-go.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DB_PASS: ${{ secrets.DB_PASS }}
