name: Deploy
on:
  push:
    branches:
      - release

permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  deploy-client:
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  deploy-users:
    uses: ./.github/workflows/deploy-users.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
  deploy-auth:
    uses: ./.github/workflows/deploy-auth.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  deploy-notes:
    uses: ./.github/workflows/deploy-notes.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
        # deploy-utils:
        #   uses: ./.github/workflows/deploy-utils.yml
        #   secrets:
        #     GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        #     DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
        #     SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
