name: Deploy
on:
  push:
    branches:
      - release/**
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-utils:
    uses: ./.github/workflows/lint-utils.yml
  lint-users:
    uses: ./.github/workflows/lint-users.yml
  lint-notes:
    uses: ./.github/workflows/lint-notes.yml
  lint-posts:
    uses: ./.github/workflows/lint-posts.yml
  deploy-client:
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - lint-client
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
