name: Deploy Client

on:
  push:
    branches:
      - release-client
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true

env:
  GAR_LOCATION: europe-north1
  PROJECT_ID: rusve-384620
  REPOSITORY: rusve-repo
  SERVICE: client
  REGION: europe-north1
  ENV: production
  COOKIE_DOMAIN: .rusve.app
  PUBLIC_AUTH_URL: https://auth-cdb5ecy4ia-lz.a.run.app
  USERS_URI: users-cdb5ecy4ia-lz.a.run.app
  NOTES_URI: notes-cdb5ecy4ia-lz.a.run.app
  UTILS_URI: utils-cdb5ecy4ia-lz.a.run.app
  UPSEND_KEY: UPSEND_KEY

permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  lint:
    uses: ./.github/workflows/lint-client.yml
  deploy:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
      - name: Build and Push Container
        run: |
          docker build -f ./client/Dockerfile -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./client \
          --build-arg ENV=${{ env.ENV }} \
          --build-arg COOKIE_DOMAIN=${{ env.COOKIE_DOMAIN }} \
          --build-arg PUBLIC_AUTH_URL=${{ env.PUBLIC_AUTH_URL }} \
          --build-arg USERS_URI=${{ env.USERS_URI }} \
          --build-arg NOTES_URI=${{ env.NOTES_URI }} \
          --build-arg UTILS_URI=${{ env.UTILS_URI }} \
          --build-arg UPSEND_KEY=${{ env.UPSEND_KEY }}

          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
