name: Lint Auth
on:
  workflow_call:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service-auth
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install nightly
      - run: rustup default nightly
      - run: rustup component add clippy-preview
      - run: cargo clippy --all-targets --all-features
