name: Lint Oauth
on:
  workflow_call:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service-oauth
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features
