name: Lint Users Rust
on:
  workflow_call:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./service-users-rust
    steps:
      - uses: actions/checkout@v3
      - run: RUSTFLAGS="--cfg uuid_unstable" cargo clippy
