name: Lint Client
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: cp .env.example .env
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run check
