name: Lint Client
on:
  workflow_call:

env:
  ENV: development
  COOKIE_DOMAIN: .127.0.0.1
  PUBLIC_SERVER_HTTP: http://127.0.0.1:8090
  USERS_URI: service-users
  UTILS_URI: service-utils
  NOTES_URI: service-notes
  STRIPE_API_KEY: STRIPE_KEY
  UPSEND_KEY: UPSEND_KEY 

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
      - run: npm run lint
      - run: npm run check
