name: Pull Request

on:
    pull_request:

permissions:
    contents: write
    id-token: write
    checks: write

jobs:
    lint-client:
        uses: ./.github/workflows/lint-client.yml
    lint-users:
        uses: ./.github/workflows/lint-users.yml
    lint-users-go:
        uses: ./.github/workflows/lint-users-go.yml
    lint-notes:
        uses: ./.github/workflows/lint-notes.yml
    lint-notes-go:
        uses: ./.github/workflows/lint-notes-go.yml
