name: Pull request
on:
  pull_request:
jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-utils:
    uses: ./.github/workflows/lint-utils.yml
  lint-users:
    uses: ./.github/workflows/lint-users.yml
  lint-notes:
    uses: ./.github/workflows/lint-notes.yml
