name: Pull request

on:
  pull_request:

permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  lint-utils:
    uses: ./.github/workflows/lint-utils.yml
  lint-users:
    uses: ./.github/workflows/lint-users.yml
  lint-notes:
    uses: ./.github/workflows/lint-notes.yml
  lint-posts:
    uses: ./.github/workflows/lint-posts.yml
